[package]
name = "rclrs_tests_with_messages"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rclrs = { version = "0.2", features = ["dyn_msg"] }
rclrs_example_msgs = "0.2"
